bin/console doctrine:query:sql "INSERT INTO category (name) VALUE ('PHP');"
bin/console doctrine:query:sql "INSERT INTO category (name) VALUE ('JS');"
bin/console doctrine:query:sql "INSERT INTO category (name) VALUE ('HTML/CSS');"
bin/console doctrine:query:sql "INSERT INTO category (name) VALUE ('Ruby');"
bin/console doctrine:query:sql "INSERT INTO category (name) VALUE ('Python');"
bin/console doctrine:query:sql "INSERT INTO category (name) VALUE ('Linux/shell');"
bin/console doctrine:query:sql "INSERT INTO category (name) VALUE ('Base de données');"
bin/console doctrine:query:sql "INSERT INTO keyword (name) VALUE ('tuto');"
bin/console doctrine:query:sql "INSERT INTO keyword (name) VALUE ('theorie');"
bin/console doctrine:query:sql "INSERT INTO keyword (name) VALUE ('accessibilité');"
bin/console doctrine:query:sql "INSERT INTO keyword (name) VALUE ('sécurité');"
bin/console doctrine:query:sql "INSERT INTO keyword (name) VALUE ('bonne pratique');"
bin/console doctrine:query:sql "INSERT INTO keyword (name) VALUE ('exemple');"
bin/console doctrine:query:sql "INSERT INTO keyword (name) VALUE ('OOP');"
bin/console doctrine:query:sql "INSERT INTO keyword (name) VALUE ('cours WCS');"
bin/console doctrine:query:sql "INSERT INTO keyword (name) VALUE ('objet connecté');"
bin/console doctrine:query:sql "INSERT INTO keyword (name) VALUE ('nabaztag');"
bin/console doctrine:query:sql "INSERT INTO keyword (name) VALUE ('serveur');"
bin/console doctrine:query:sql "INSERT INTO keyword (name) VALUE ('outil');"
